eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    fetchRegistry: false
    healthcheck:
      enabled: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    peer-node-read-timeout-ms: 3000
server:
  port: 8761
spring:
  application:
    name: eurekaserver
  cloud:
    client:
      ip-address: 127.0.0.1
    inetutils:
      preferred-networks: 127.0.0.1
