eureka:
  instance:
    prefer-ip-address: true	 #是否以 IP 注册到注册中心，Eureka 默认是以 hostname 来注册的
    hostname: ${spring.cloud.client.ip-address} #设置当前实例的主机名称
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} #实例id: 服务名:ip:端口
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: feign
feign:
  hystrix:
    enabled: true #开启熔断器
ribbon:
  eureka:
    enable: true #Feign 默认集成了 Ribbon，默认实现了负载均衡
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
management:
  endpoints:
    web:
      exposure:
        include: "*" #访问/actuator/hystrix.stream能看到不断更新的监控流 或 include: ['hystrix.stream','info','health']
