eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: feign
feign:
  hystrix:
    enabled: true #开启熔断器
ribbon:
  eureka:
    enable: true #Feign 默认集成了 Ribbon，默认实现了负载均衡
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
management:
  endpoints:
    web:
      exposure:
        include: "*" #访问/actuator/hystrix.stream能看到不断更新的监控流 或 include: ['hystrix.stream','info','health']
